image: creatiwww/docker-compose:latest

services:
  - docker:dind

variables:
  GIT_CLEAN_FLAGS: none

stages:
  - deploy

step-deploy-dev:
  stage: deploy
  only:
    - development
  tags:
    - development-ci
  script:
    - echo "Development deploy start..."
    - docker build --no-cache --build-arg uid=$(id -u) --build-arg gid=$(id -g) .
    - docker run --rm -u "$(id -u):$(id -g)" -v "$(pwd):/var/www/html" -w /var/www/html laravelsail/php81-composer:latest composer install --ignore-platform-reqs
    - ./vendor/bin/sail up -d
    - ./vendor/bin/sail artisan storage:link
    - ./vendor/bin/sail artisan module:migrate
    - ./vendor/bin/sail npm install
    - ./vendor/bin/sail npm run build
    - echo "Development deploy end"

step-deploy-prod:
  stage: deploy
  only:
    - main
  tags:
    - production-ci
  script:
    - echo "Production deployment start..."
    - docker build --no-cache --build-arg uid=$(id -u) --build-arg gid=$(id -g) .
    - docker run --rm -u "$(id -u):$(id -g)" -v "$(pwd):/var/www/html" -w /var/www/html laravelsail/php81-composer:latest composer install --ignore-platform-reqs
    - ./vendor/bin/sail up -d
    - ./vendor/bin/sail artisan storage:link
    - ./vendor/bin/sail artisan module:migrate --seed
    - ./vendor/bin/sail npm install
    - ./vendor/bin/sail npm run build
    - echo "Production deployment end"